language: node_js
node_js:
  - "8.14"
env:
  - TEST_DB_URL='mysql://travis:@localhost/amb_site_test' COOKIE_SECRET='keyboard_cat' RESET_KEY='alphabet_soup'
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE amb_site_test'
  ### the below commands are for greenkeeper-lockfile - needed for greenkeeper
  ### greenkeeper is a service used to keep dependencies up to date - the greenkeeper-lockfile
  ### code makes sure that package-lock.json gets updated at the same time as the package.json
  ### Requires GH_TOKEN set in CI settings to a write-access github token
  ### https://github.com/greenkeeperio/greenkeeper-lockfile
  - '[[ $(node -v) =~ ^v9.*$ ]] || npm install -g npm@latest' # skipped when using node 9
  - npm install -g greenkeeper-lockfile@1
install:
  - npm install
before_script:
  - greenkeeper-lockfile-update
script:
  - npm run lint
  - npm test
after_script:
  - greenkeeper-lockfile-upload